### PR TITLE
Adding mlh edits

### PR DESCRIPTION
**Pull request by uptonm**

### CODE REVIEW

**Comment by ShawnToubeau** [comment]
and @uptonm can you remove the MLH banner too?

**Comment by uptonm** [comment]
Oof, my bad

Michael Upton
uptonm@wit.edu
BSCS Computer Science, 2020
Wentworth Institute of Technology
________________________________

**Comment by uptonm** [comment]
@ShawnToubeau fixed the date, the mlh banner is commented out btw

**Comment by uptonm** [comment]
alright deploying rn

**Pull request merged**
