### PR TITLE
Added/Updated Sponsorship Logos to site

### PR DESCRIPTION
**Pull request by corbinhak**

### CODE REVIEW

**Comment by uptonm** [comment]
When you are ready, you can merge this. Do you know how to deploy to the site?

**Comment by corbinhak** [comment]
Its not ready to merge just yet.

**Comment by uptonm** [comment]
ahh no worries, just lmk when it is and I can show you how to deploy if you dont already know 😃

**Comment by corbinhak** [comment]
Alright updated to the best of my ability. Feel free to clone and test before merging.

**Comment by corbinhak** [comment]
Fixed and updated by Mike

**Pull request closed without merging**
